name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Switch to Ubuntu runner

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run .NET tests
        run: dotnet test

      - name: Publish .NET application
        run: dotnet publish -c Release -o published

      - name: Start .NET application (production mode)
        run: |
          cd published 
          nohup dotnet YourProjectName.dll &  # Use nohup to run in the background and ignore hangup signals

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run Postman/booking_tests.json -k -r cli