name: .NET Build and Test

env:
  ASPNETCORE_URLS: 'https://+:5001;http://+:5000'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run .NET tests
        run: dotnet test

      - name: Run
        run: dotnet run --no-build --urls "http://localhost:5000" &
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://localhost:5000
          
      - name: Check app health
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:5000); do
            echo "Waiting for app to launch..."
            sleep 5
          done

      - name: Check port with netstat
        run: netstat -an | findstr "LISTENING"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run Postman/booking_tests -k