name: .NET Core CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_URLS: 'https://+:5001;http://+:5000'

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Or your desired .NET version

      - name: Build
        run: dotnet build HotelBooking.WebApi/HotelBooking.WebApi.csproj --configuration Release

      - name: Start .NET application (background)
        run: |
          nohup dotnet $(Build.SourcesDirectory)/HotelBooking.WebApi/bin/Release/HotelBooking.WebApi.dll &  # Adjust the path if needed

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run $(Build.SourcesDirectory)/Postman/HotelBooking.postman_collection.json -k -r cli